export default [
  {
    id: "1",
    title: "Xu hướng màu sắc nhà tắm 2023",
    image: '/img/blog1.jpg' ,
    body: "<p><h2>Màu đen - màu sắc gây ấn tượng.</h2> Hãy cùng khám phá gam màu đậm nhất: Đen. Màu sắc đại diện cho sức mạnh, quyền lực và uy quyền sẽ không lấn át không gian cá nhân này. Nhờ tính hình thức và sang trọng, nó đang trở nên phổ biến như một màu chủ đạo trong nhà tắm. Màu đen có tác dụng làm ấm hoặc tạo ra một cái nhìn tối giản, tùy thuộc vào mục đích của bạn. Màu đen gợi lên những cảm xúc mạnh mẽ và luôn mang lại vẻ hiện đại, tạo cho phòng tắm của bạn đẹp vượt thời gian.</p> <p><h2>Màu trắng - màu sắc của sự tươi mát.</h2> Nếu bạn hướng đến sự mát mẻ và đơn giản, lựa chọn một căn phòng tắm toàn màu trắng là điều không bao giờ sai. Màu trắng mang lại khởi đầu mới mẻ làm tăng năng lượng cho một ngày mới. Hậu đại dịch covid, màu trắng được xếp hạng cao nhờ cảm giác sạch sẽ và tinh khiết nó mang lại. Gam màu sáng này còn giúp không gian phòng tắm trông gọn gàng và thoáng đãng hơn. Phòng tắm với gam màu trắng sẽ làm cho không gian rộng rãi tạo cảm cho bạn giác thư giãn. Từ đó, dễ dàng sáng tạo hơn. </p>",
    bookmark: true,
  },
  {
    id: "2",
    title: "Tối ưu hóa diện tích cho căn bếp nhỏ",
    image: '/img/blog2.jpg',
    body: "<p><h2>Tối ưu hóa không gian và che đi những sự lộn xộn<h2>Cách tiếp cận theo mô-đun đáp ứng nhu cầu của tất cả mọi thành viên trong gia đình là cách tốt nhất. Các giải pháp đa chức năng giúp cô đọng và tối đa hóa diện tích sẽ tiết kiệm thời gian và tiền bạc. Mở rộng các kệ bếp trên cao và âm bàn, thêm các kệ xoay tầng tại các góc nhà, thiết kế lại các bề mặt có thể kéo ra như ngăn kéo, lựa chọn các sản phẩm mặt bàn và chậu rửa thiết kế thông minh là các giải pháp để tối ưu hóa không gian sẵn có. Nhà bếp cần có sự linh hoạt để đáp ứng nhu cầu của nhiều nhóm thành viên trong gia đình và các bữa tiệc khác nhau. Các món nội thất đa năng như bàn có kể mở rộng được để tổ chức tiệc tối cho nhiều thành viên – hay các ngăn tủ âm tường, hệ thống của trượt giúp tiết kiệm không gian. Nó có thể chứa rất nhiều đồ đồng thời ẩn các thiết bị và dụng cụ vào trong giúp mang lại vẻ gọn gàng tươm tất cho không gian.</p> <p><h2>Sử dụng các nội thất đa năng để cải thiện tính linh hoạt</h2>Khi nhà bếp giờ đây có xu hướng thành một phần mở rộng của phòng khách, khu mặt bàn và chậu bếp trở thành nơi được sử dụng nhiều nhất, nó cũng có chức năng như một quầy bar để mọi người cùng nhau thưởng thức nước uống. Các thiết kế tất-cả-trong-một tiện dụng cho nhiều mục đích sử dụng khác nhau giúp khuyến khích gia đình dành thêm nhiều thời gian bên nhau và đáp ứng nhu cầu lưu trữ nhiều đồ đạc. Mặt bàn và bộ chậu rửa đa năng sẽ giúp tăng tốc độ cho các “bếp trưởng” trong gia đình. Nó giúp giải quyết và tăng hiệu quả việc bếp núc nhanh hơn, đồng thời khi nấu ăn vẫn có thể tương tác với khách và có thể dễ dàng với tới các dụng cụ cần để nấu ăn.</p><p><h2>Sử dụng màu sắc và các chất liệu để tỏa sáng</h2>Bên cạnh phần cứng, thiết kế nhà bếp đương đại bao gồm màu sắc, vật liệu và hoàn thiện. Diện mạo không gian bắt mắt giúp thu hút người dùng dành nhiều thời gian hơn trong phòng. Các màu sắc phổ biến như màu hồng dịu nhẹ, màu xanh lam và xanh lá cây nhẹ nhàng, lấy cảm hứng từ thiên nhiên mang đến sự vui tươi và thú vị. Thêm một chút sắc sảo với các bề mặt và đồ trang trí bằng kim loại sáng lấp lánh, chẳng hạn như bồn rửa bằng thép không gỉ có thể phản chiếu với ánh sáng, mang đến cho phong cách đơn sắc một nét khác biệt. Màu sắc, hình dáng, bề mặt nhẵn và bóng của bồn rửa bằng thép không gỉ là niềm tự hào của người đầu bếp sành điệu.</p>",
    bookmark: false,
  },
  {
    id: "3",
    title: "Những lưu ý khi chọn màu cho nội thất",
    image: '/img/blog3.jpg',
    body:"<p><h2>Sử dụng các màu an toàn</h2>Màu sắc vô cùng đa dạng, muôn hình muôn vẻ, mỗi màu lại có thể phối hợp một cách hài hòa với một hay nhiều màu sắc khác. Tuy nhiên, có một vài sắc độ được xem là “màu an toàn”. Những màu này có thể kết hợp với rất nhiều kiểu màu cũng như phong cách thiết kế khác nhau, không bị ảnh hưởng bởi các xu hướng mà cực kỳ bền vững với thời gian: Màu đen: Không cần bàn cãi, một màu trung tính mang vẻ hiện đại, lịch lãm mà có thể phối với hầu hết các gam màu. Màu trắng: Sáng sủa, thoáng đãng và trang nhã, màu trắng là lựa chọn hợp lý cho mọi phong cách thiết kế. Màu nâu: Vốn được xem là màu của giới thượng lưu, màu nâu đem lại vẻ sang trọng, giàu sang và cổ điển, mang lại vẻ đẹp vượt thời gian mà không một ai có thể phủ nhận được. Màu xám: Màu sắc đem lại cảm giác hiện đại nhiều nhất, với sự mạnh mẽ nhưng lịch lãm, thông thoáng nhưng rất ấm áp, đưa sự tiên tiến trong lối phối màu vào các thiết kế của bạn.</p> <p><h2>Tạo điểm nhấn với màu nổi bật</h2>Tất nhiên, không hề có một quy luật nào ràng buộc bạn với duy nhất một lối thiết kế dựa trên một bảng màu nhất định cả. Không gian sống là của riêng bạn, và bạn hoàn toàn có thể tô điểm nó bằng những màu sắc nổi trội, tạo điểm nhấn cho không gian thêm thú vị và bắt mắt. Hãy hình dung một căn phòng với lối phối màu hiện đại giữa các tông màu mát, được tô điểm bởi một chiếc ghế với tông màu ấm nội bật. Chắc hẳn căn phòng sẽ trở nên đa dạng hơn, tạo sự khác biệt nhưng vẫn giữ được nét hài hòa vốn có.</p>",
    bookmark: false,
  },
];
